### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by LimeBlast** [wejn/ws2812#1]
Hi, I'm trying to install this gem on my Raspberry Pi 2, but I'm getting the following error message:

```
pi@babblepi:~ $ sudo gem install ws2812
Fetching: ws2812-0.0.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ws2812:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.1.0/gems/ws2812-0.0.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/ws2812-0.0.2/gem_make.out
```

I'm running the latest version of Raspbian, via NOOBS 1.8
# Update 1

I've just installed ruby2.2-dev via `sudo apt-get install ruby2.2-dev` then tried again, and got a new error message:

```
pi@babblepi:~ $ sudo gem install ws2812
Building native extensions.  This could take a while...
ERROR:  Error installing ws2812:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
creating Makefile

make "DESTDIR=" clean
rm -f Makefile

make "DESTDIR="
make: *** No targets specified and no makefile found.  Stop.

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.1.0/gems/ws2812-0.0.2 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/ws2812-0.0.2/gem_make.out
```
# Update 2

Having just followed the manual install instructions, I'm now getting yet another error message:

```
pi@babblepi:~/Git/ws2812 $ sudo ruby examples/digiclock.rb
/home/pi/Git/ws2812/lib/ws2812/basic.rb:80:in `open': init failed with code: -1, perhaps you need to run as root? (RuntimeError)
        from /home/pi/Git/ws2812/lib/ws2812/unicornhat.rb:30:in `initialize'
        from examples/digiclock.rb:97:in `new'
        from examples/digiclock.rb:97:in `<main>'
pi@babblepi:~/Git/ws2812 $
```

**Comment by Gadgetoid** [comment]
It looks like you're pretty much set to go, however the underlying C code does not support the Pi 2 or Pi 3. I've submitted a PR to fix this: https://github.com/wejn/ws2812/pull/2

In the mean time, you can get the updated code from my fork! I've tested it briefly, and it seems to work like a charm. Loving the cross-fading digital clock example!

**Comment by wejn** [comment]
Perfect, thank you for this.

**Comment by LimeBlast** [comment]
Hi, sorry about this @wejn, but upon trying to install this via `sudo gem install ws2812`, I'm still unable to make it work:

```
sudo gem install ws2812
Fetching: ws2812-0.0.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ws2812:
        ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.1 extconf.rb
creating Makefile

make "DESTDIR=" clean
rm -f Makefile

make "DESTDIR="
make: *** No targets specified and no makefile found.  Stop.

make failed, exit code 2

Gem files will remain installed in /var/lib/gems/2.1.0/gems/ws2812-0.0.4 for inspection.
Results logged to /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/ws2812-0.0.4/gem_make.out
```

**Comment by Gadgetoid** [comment]
I ran into this same problem attempting to build the gem with Rake and install it locally.

From what I understand, `extconf.rb` is responsible for creating the makefile, and is also opening up the result and adding some extra targets. Something's going awry in this process!

**Comment by Gadgetoid** [comment]
Can confirm, opening `ext/ws2812/extconf.rb` and removing the extra gumph at the bottom ( note, I don't actually know what this is for ):

```
File.open('Makefile', 'at') do |mk|
    mk.puts <<EOF
clean: clean-rpilowlevel
distclean: distclean-rpilowlevel

clean-rpilowlevel:
    rm -f Makefile

distclean-rpilowlevel:
    rm -f *_wrap.c
EOF
end
```

As far as I know, it's safe to run SWIG as part of the deployment process and ship a precompiled wrapping file in a package.

**Comment by wejn** [comment]
OK, sorry about that. I should be back from my out-of-country
trip on Friday so I'll look into it.

In the meantime, if you want to fix it, then just remove
the extra stuff (it's just my half-assed attempt at a cleanup
job), bump version of the gem in lib/ws2812.rb and run the
rake gem task.

Should give you a gem that will pretty much mimic what I'm
about to do when I get to it on Friday (minus the fact
I'll try and put the cleanup somewhere else plus will run
a few tests on an actual RPi to confirm that it definitely
positively builds OK this time around).

Cheers,

Michal

PS: As usual, sorry for the late responses. Work's been
    crazy intense past few weeks.

On Tue, 22 Mar 2016, Philip Howard wrote:

> Can confirm, opening `ext/ws2812/extconf.rb` and removing the extra gumph at the bottom ( note, I don't actually know what this is for ):
> 
> ```
> File.open('Makefile', 'at') do |mk|
>   mk.puts <<EOF
> clean: clean-rpilowlevel
> distclean: distclean-rpilowlevel
> 
> clean-rpilowlevel:
>   rm -f Makefile
> 
> distclean-rpilowlevel:
>   rm -f *_wrap.c
> EOF
> end
> ```
> 
> As far as I know, it's safe to run SWIG as part of the deployment process and ship a precompiled wrapping file in a package.
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/wejn/ws2812/issues/1#issuecomment-200033506

## 

Michal J. <box(at)wejn.org>
"I honestly think it is better to be a failure at something you love
than to be a success at something you hate..." -- George Burns

**Comment by LimeBlast** [comment]
I'm totally new to the development side of gems (my experience this far is mostly confined to adding gems to my `Gemfile` and running `bundle install`), but after a bit of trial and error, I think I've managed to make this work.

The steps I followed (for my own potential future reference) are:
1. Installed Ruby 2.1 Dev:
   - `sudo apt-get install ruby2.1-dev`
2. Removed the section of code [listed here](https://github.com/wejn/ws2812/issues/1#issuecomment-200033506) from the `ext/ws2812/extconf.rb` file.
3. Updated the version number in `lib/ws2812.rb`.
4. Installed Rake:
   - `sudo gem install rake`
5. Installed Rake-compiler:
   - `sudo gem install rake-compiler`
6. Run the rake gem task:
   - `rake gem`
7. Installed the freshly created gem:
   - `cd pkg`
   - `sudo gem install ws2812-x.x.x.gem`

I then went on to test in a couple of ways - most obvious of which was to see it in the output of `gem list` - but the real test was getting it to run the `digiclock.rb` file successfully, which I did by moving it into my home directory, commenting out [line 2](https://github.com/wejn/ws2812/blob/master/examples/digiclock.rb#L2), then running it - which worked fantasticly :+1: 

I'm looking forward to this being updated in rubygems, without the need for all the steps listed above, but for the moment, with what I'm looking to do with it, I'm sated.

Thank you both.

**Comment by LimeBlast** [comment]
This might be obvious to anyone who actually knows what they're doing - but as this is all new to me, I figured it was important enough to post here... That being, I've been able to follow [my own instructions](https://github.com/wejn/ws2812/issues/1#issuecomment-201377579) to make this work on [Ubuntu MATE](https://ubuntu-mate.org/raspberry-pi/).

@wejn any updates on when the gem will be updated on rubygems?

Again, thank you :smiley:

**Comment by LimeBlast** [comment]
... or, as it turns out.. maybe not :confused:

It worked fine when I first did it, now, after having rebooted, it's now just flashing lights like crazy:

https://vine.co/v/ijQT6jOzjnB

Not sure if this is something specific to Ubunutu MATE, or something else, but it's most unexpected.

---

UPDATE: It seems to work fine when the monitor is plugged in (at least this has been my experience with it so far).

UPDATE 2: I've been able to make it work as intended by disabling the graphical interface on boot by [following these instructions](https://ubuntu-mate.community/t/solved-boot-raspberry-pi-2-image-directly-to-terminal-console/1569/3) - this allows me to boot the pi without an attached monitor, and lets the UnicornHAT work as intended... No idea what's going on with that, but it's a suitable solution for now.

**Comment by wejn** [comment]
@LimeBlast 0.0.6 is out. Sorry it took so long. My work is taking all my free time at this moment. :-(

This version also fixes accidental breakage caused by @Gadgetoid's pull request (see 69195f827052e30f989e8502f0caabb19b343dfd if interested)

**Comment by LimeBlast** [comment]
Thank you very much, I'll have a play with that later.

**Comment by Gadgetoid** [comment]
@wejn did you mean the DMA error handling in ext/ws2812/ws2811.c?

**Comment by wejn** [comment]
@Gadgetoid yes. Because I really hate libraries that printf() all over the place. That's why I killed all the outputs and reverted to using errors/errnos.
